# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_owner',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='test',
        ),
    ]
