# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 00:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('correct_answer', models.CharField(max_length=50)),
                ('wrong_answer_1', models.CharField(max_length=50)),
                ('wrong_answer_2', models.CharField(max_length=50)),
                ('wrong_answer_3', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User')),
            ],
        ),
    ]
