# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20160214_0028'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='answers', to='answers.Answer'),
        ),
    ]
