# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='Test 1', max_length=20),
            preserve_default=False,
        ),
    ]
